### ISSUE TITLE
9.0.10 error

### ISSUE THREAD

**Issue by vaniron** [Daniel-Forge-Development/PokeTracker#4]
Plugins works most of the time, just sometimes refuses to do its job due to: https://pastebin.com/raw/4mT77yrM

**Comment by aglarcz** [comment]
Issue on our end - corrupted server files.

**Comment by vaniron** [comment]
thought it was due to server files being corrupted but obviously not - this issue still occuring

**Comment by danorris709** [comment]
Do you have any custom datapacks? `return new SpriteTransformer(species.getDefaultForm().getDefaultGenderProperties().getDefaultPalette().getSprite().toString());`

**Comment by vaniron** [comment]
Nothing with custom textures/forms or any pokemon modifications.

**Comment by vaniron** [comment]
Still occuring on 9.0.11.

**Comment by danorris709** [comment]
Fixed in upcoming version
