### ISSUE TITLE
[Poketracker 1.0.3-1.16.5] Pokemon display as "despawned" and "active" when caught and sent out.

### ISSUE THREAD

**Issue by KittyKatzyn** [Daniel-Forge-Development/PokeTracker#5]
With PokeTrackerPlaceholders-2.9.7-1.16.5.jar, PokeTracker displays caught pokemon as "Despawned" and said pokemon when sent out of pokeballs as "active", rather than as "caught".

1) Find shiny.
2) /poketracker shows shiny as "Active". (Intended)
3) Catch shiny.
4) /poketracker shows shiny as "Despawned". (not intended - should says "caught")
5) Send shiny out of pokeball.
6) Tracker shows shiny as "Active". (should say "caught")

https://discord.com/channels/831966641586831431/1080374033327063050

**Comment by danorris709** [comment]
Fixed by latest I believe
